version: "3.1"

services:
  frontend:
    build:
      context: ../
      dockerfile: ./dockerFiles/client/Dockerfile.dev
    container_name: frontend
    volumes:
      - ../client:/usr/src/app
    ports:
      - 3000:3000
  backend:
    build:
      context: ../
      dockerfile: ./dockerFiles/server/Dockerfile.dev
    container_name: backend
    volumes:
      - ../server:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
