version: "3.1"

services:
  client:
    build:
      context: ../
      dockerfile: ./dockerFiles/client/dockerFile.dev
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  server:
    build:
      context: ../
      dockerfile: ./dockerFiles/client/dockerFile.dev
    volumes:
      - ./server:/app
    ports:
      - 5000:5000

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
